### ISSUE TITLE
The bot dose not work

### ISSUE THREAD

**Issue by nasseralharbi12** [abdullah-cafer/MudaRemote#1]
I've tried to run the bot but I had an issue 

Exception in thread Thread-1 (run_bot):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()

**Comment by abdullah-cafer** [comment]
did you create a presets file
create and enter the required values and try again

**Comment by nasseralharbi12** [comment]
I did but still same error
?] Please select an option::
 > Select and Run Preset
   Select and Run Multiple Presets
   Exit

[?] Select a preset to run::
 > preset1
   preset2
   preset3

Exception in thread Thread-1 (run_bot):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
[?] Please select an option::
    self.run()
 > Select and Run Preset
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
   Select and Run Multiple Presets

**Comment by abdullah-cafer** [comment]
Have you done everything in the readme
make sure you use the preset file from the repo and install the necessary libraries
